emcrisostomo/fswatch

libfswatch/src/libfswatch/c/cevent.h
libfswatch/src/libfswatch/c/libfswatch.cpp
libfswatch/src/libfswatch/c/libfswatch.h

I found myself needing to pass extra data on the C API callbacks. I think its useful in general, cause you can't always rely on global data in the callbacks.
I'm open to suggestions on how this should be named.

Attach additional data to C API monitor callbacks

---

libfswatch/src/libfswatch/c++/inotify_monitor.cpp

- `NAME_MAX` is not in `limits.h` on Illumos.
I'm really not sure where to target this.  I read `CONTRIBUTING.md` and picked develop as the closest thing to a hotfix branch for 1.6.0.  I hope that is is okay.
My commit it based on 1.6.0 to hopefully make integration easier.  It applies cleanly to both **master** and **develop**.
Let me know if I've done this wrong and I'll gladly retarget and create a new PR :)

Allow build on Illumos

---

libfswatch/src/libfswatch/c/cevent.h
libfswatch/src/libfswatch/c/cfilter.h
libfswatch/src/libfswatch/c/libfswatch.h

Hi there,
Just fixed the C headers compilation issues, these are the changes I propose. Now one of the issues dealt with a C++ default function argument.
```
FSW_HANDLE fsw_init_session(const enum fsw_monitor_type type/* = system_default_monitor_type*/);
```
In C there are no default arguments, therefore I believe tha C source sample code should be updated to reflect this. You can either make the selection up to the user of your library or fix it internally. I'm a user and I have no issue what so ever with setting the monitor_type before usage.
Secondly, when building a C program using the headers linkage should be against a dynamic library in order to find all missing C++ symbols i.e.
```
$ gcc -I /usr/local/include -o "fswatch_test" fswatch_test.c /usr/local/lib/libfswatch.dylib
``` …

Fixed headers for c compilation

---

man/fswatch.7.in

- Fixed .Nm. -> .Nm - missed macro
- .UR and .UE don't work correct in and trigger warnings about not defined
macros - so i guess a pure link is the better idea.

Fix manpage generation

---

README.md

Remove the number of monitors because there are more than four kinds of monitors listed.

Fix wording for monitor list

---

libfswatch/src/libfswatch/c++/fsevents_monitor.cpp

If you stop monitor right after starting it in a separate thread - it might result in `segfault` and warnings like these:
```
2017-11-23 23:42 ruby[9437] (FSEvents.framework) streamRef->cfRunLoopSourceRef != NULL || streamRef->event_source != NULL(): failed assertion: Must call FSEventStreamScheduleWithRunLoop() before calling FSEventStreamInvalidate()
2017-11-23 23:42 ruby[9437] (FSEvents.framework) streamRef->cfRunLoopSourceRef == NULL && streamRef->event_source == NULL(): failed assertion: FSEventStream was released (causing it to be deallocated) without calling FSEventStreamInvalidate()
```
Code to reproduce (slightly modified `test/src/fswatch_test.c`) https://gist.github.com/t3hk0d3/a37fa9ca515ad27bbb8b756120828587
Idea is to have FSEvents deinitialization logic on same thread as …

Fix stop sequence for FSEvents monitor

---

libfswatch/src/libfswatch/c/cevent.h
libfswatch/src/libfswatch/c/libfswatch.cpp

I've decided to group several fixes into single PR, instead of having them separately.
- Fix `cevent.h` not being C99 compliant (C++ stuff leaking into C headers)
- Fix session struct not being destroyed.
Debatable change, might potentially break existing code. However documentation says: 
> Destroys an existing session and __invalidates its handle__.
- Fix segfault during `fsw_start_monitor` if there is errors inside `create_monitor` (for example callback is not set)

Fix several issues

---

configure.ac

Whilst working on the Reproducible Builds effort [0], we noticed
that fswatch could not be built reproducibly.
This is because the manpage used the output of the date(1) cmd.
This has been filed in Debian as #882818 [1].
[0] https://reproducible-builds.org/
[1] https://bugs.debian.org/882818

Make the build reproducible.

---

configure.ac
libfswatch/src/libfswatch/Makefile.am
libfswatch/src/libfswatch/libfswatch.pc.in

I wanted to get this to work with pkg-config because it makes it convenient to add `libfswatch` as a dependency to other automake based projects via `PKG_CHECK_MODULES`.
Since it works for my purposes now, I decided to make this PR in case you're interested in integrating this upstream ^^

Integrate with pkg-config

---

configure.ac

using both AC_CONFIG_MACRO_DIR and AC_CONFIG_MACRO_DIRS is deprecated in autoconf-2.71

using both AC_CONFIG_MACRO_DIR and AC_CONFIG_MACRO_DIRS is deprecated in autoconf-2.71

---

fswatch/src/fswatch.cpp

simple type mistake, only reproduct on macOS (?)
'optarg' is a global variable, can be used directly, 
but macOS choked on that , 
and I see all other functions passing a parameter instead the global variable, 
so here just add a function parameter.
Signed-off-by: yunh <haihai107@126.com>

fix compile error on macOS

---

libfswatch/src/libfswatch/c++/fsevents_monitor.cpp

As proposed in https://github.com/emcrisostomo/fswatch/issues/243#issuecomment-642493362, send `AttributeModified` in response to `kFSEventStreamEventFlagItemInodeMetaMod`.

Send AttributeModified on touch when using the FSevents monitor

---

README.libfswatch.md
README.md
libfswatch/src/libfswatch/c/libfswatch.cpp

Hi,
Thank you for this amazing pice of code.
I've created `libfswatch` bindings for Go that expose all the library's features in an idiomatic way: https://github.com/dunglas/go-fswatch
This patch adds references to these bindings in the documentation. Feel free to close the PR if you don't want to add references to a third-party package (which would be completely understandable).
Cheers,

docs: add references to Go bindings

---

README.freebsd

FreeBSD used to ship an old version of GCC in the base system but this is not the case for any supported version (and has not been the case for many years).  Update the note in README.freebsd to reflect this.

README.freebsd: remove no longer applicable GCC comment

---

libfswatch/src/libfswatch/c++/kqueue_monitor.cpp
libfswatch/src/libfswatch/c++/path_utils.cpp
libfswatch/src/libfswatch/c++/path_utils.hpp
libfswatch/src/libfswatch/c++/poll_monitor.cpp

As of current `fswatch`, the behaviour of `kqueue_monitor` and `poll_monitor` is such that the `--follow-links` option would be honored for root paths, but then symlinks would always be followed. With this change, `--follow-links` would be honored for symlinks at any depth into a file hierarchy

Refactor path handling for conditional symlink handling at all levels

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
CMakeLists.txt
NEWS
libfswatch/src/libfswatch/c++/event.cpp
libfswatch/src/libfswatch/c++/inotify_monitor.cpp
libfswatch/src/libfswatch/c++/kqueue_monitor.cpp
libfswatch/src/libfswatch/c++/monitor.cpp
libfswatch/src/libfswatch/c++/poll_monitor.cpp
libfswatch/src/libfswatch/c/cevent.cpp
libfswatch/src/libfswatch/c/cevent.h
m4/fswatch_version.m4
m4/libfswatch_version.m4

* Added event flag CloseWrite: file open for write has been closed. 
* kqueue_monitor: added support for CloseWrite, adding support for events of
type NOTE_CLOSE_WRITE.
* inotify_monitor: added support for CloseWrite, adding support for events of
type IN_CLOSE_WRITE.

Add CloseWrite event flag (inotify, kqueue): file open for write has been closed.

---

CMakeLists.txt
fswatch/src/fswatch.cpp
m4/fswatch_version.m4
m4/libfswatch_version.m4
po/en.po
po/en@boldquot.po
po/en@quot.po
po/es.po
po/fswatch.pot
po/it.po

Use std::filesystem::absolute instead of std::filesystem::canonical when passing path arguments to monitors

Issue 337: fswatch exists on non existing path

---

man/fswatch.7.in

`-utf-time` should now read `-utc-time` in the `fswatch` man page.

Fix man page typo: `utf-time` -> `utc-time`

---

libfswatch/src/libfswatch/c++/inotify_monitor.cpp

Fixes https://github.com/emcrisostomo/fswatch/issues/206
This PR removes the explicit calls to `inotify_rm_watch()` in the inotify monitor destructor as these are implicitly removed when the inotify handle is closed.
The logging of the removals is retained.
According to [`inotify(7)`](https://man7.org/linux/man-pages/man7/inotify.7.html):
> When all file descriptors referring to an inotify instance have
been closed (using [close(2)](https://man7.org/linux/man-pages/man2/close.2.html)), the underlying object and its
resources are freed for reuse by the kernel; all associated
watches are automatically freed.

Fixes spurious output 'inotify_rm_watch: Invalid argument'

---

.github/workflows/cmake-libfswatch.yml
CMakeLists.txt
libfswatch/CMakeLists.txt
libfswatch/src/libfswatch/c++/path_utils.cpp
libfswatch/src/libfswatch/c++/poll_monitor.cpp
libfswatch/src/libfswatch/c++/windows/win_paths.cpp
libfswatch/src/libfswatch/c++/windows/win_strings.cpp
libfswatch/src/libfswatch/c/libfswatch.h

As I proposed in https://github.com/emcrisostomo/fswatch/issues/214#issuecomment-2639274929, and mainly based on the great work by [brechtsanders](https://github.com/brechtsanders) in #214, these are the minimal changes needed to compile 'libfswatch' using cmake, which is a step in building the R binding.
There are 2 further commits to remove warnings/errors which surface in the mandatory toolchains we have for building R packages at our central repository. These should be straightforward.
Apologies for some of the whitespace-only changes - it's just my editor...
If you're fine merging these then I'll make a cut of my R package that uses the updated library version, and you'll know that it's tested on my side at least. Conversely, for those using Windows with Cygwin, this shouldn't result …

Enable compilation of libfswatch under Windows MinGW
